# Generated by Django 6.0.2 on 2026-02-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groceryitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='groceryitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
